### ISSUE TITLE
DynamicField RenderBlock appears twice in AgentTicketPhone

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/ServiceCatalog#2]
In the ServiceCatalogPackage you have two renderblocks for DynamicFields in AgentTicketPhone.

**Comment by stefanhaerter** [comment]
I was a bit too quick, I didn't see the existing PR - fix is pushed, suggest to close the issue.

**Comment by stefanhaerter** [comment]
No further updates occured - closing the issue.
