### ISSUE TITLE
Dynamic Fields are displayed doubled in AgentTicketPhone

### ISSUE THREAD

**Issue by ybeckmann21** [RotherOSS/ServiceCatalog#8]
Dynamic Fields "Fieldset, Fehlerkategorie and Tags" get loaded doubled in AgentTicketPhone.
![grafik](https://github.com/user-attachments/assets/f6aa49e3-736b-416f-bc0a-5a05417853c9)

For some reason [% Data.DynamicFieldHTML %] appears two times in the AgentTicketPhone.tt
![grafik](https://github.com/user-attachments/assets/84b4df5d-1c61-4056-b9bf-4074333c6e7d)

Deleting one of the entries resolves the issue.
I only encounter this bug in AgentTicketPhone.

**Comment by svenoe** [comment]
Fixed in https://github.com/RotherOSS/ServiceCatalog/commit/2c1db53acf4cafae485bade73db08e0e4bd2e004
